### ISSUE TITLE
unable to find version `v1.0.0`

### ISSUE THREAD

**Issue by machour** [caffco/code-climate-github-action#504]
When using this action as documented in the readme, I get :

```
Error: Unable to resolve action `caffco/code-climate-github-action@v1.0.0`, unable to find version `v1.0.0`
```

**Comment by Sumolari** [comment]
Oh, the readme is wrong: latest published version is `0.0.1-alpha.7`, there's no version 1.0.0 yet.

You might find the latest version in the [Marketplace page](https://github.com/marketplace/actions/upload-coverage-to-code-climate).

You can use it as:

```yml
name: Test
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: before_build
        uses: caffco/code-climate-github-action@v0.0.1-alpha.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          run_before_build: 'true'
      - name: Run tests
        run: yarn test --coverage
      - name: collect_coverage
        uses: caffco/code-climate-github-action@v0.0.1-alpha.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          collect_coverage: 'true'
          coverage_file_patterns: |
            **/*.lcov:lcov
      - name: after_build
        uses: caffco/code-climate-github-action@v0.0.1-alpha.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          run_after_build: 'true'
```
